#!/bin/bash

## Author : Aditya Shakya
## Github : adi1090x

PDIR="$HOME/.config/polybar"
LAUNCH="polybar-msg cmd restart"

if  [[ $1 = "-budgie" ]]; then
# Removing Old File
rm -rf $PDIR/config.ini
# Coping New File
cp -r $PDIR/panel/budgie.ini $PDIR/config.ini
# Setting Background
feh --bg-fill $PDIR/wallpaper/budgie.jpg
# Restarting polybar
$LAUNCH &

elif  [[ $1 = "-gnome" ]]; then
# Removing Old File
rm -rf $PDIR/config.ini
# Coping New File
cp -r $PDIR/panel/gnome.ini $PDIR/config.ini
# Setting Background
feh --bg-fill $PDIR/wallpaper/gnome.jpg
# Restarting polybar
$LAUNCH &

elif  [[ $1 = "-mint" ]]; then
# Removing Old File
rm -rf $PDIR/config.ini
# Coping New File
cp -r $PDIR/panel/mint.ini $PDIR/config.ini
# Setting Background
feh --bg-fill $PDIR/wallpaper/mint.jpg
# Restarting polybar
$LAUNCH &

elif  [[ $1 = "-ubuntu_gnome" ]]; then
# Removing Old File
rm -rf $PDIR/config.ini
# Coping New File
cp -r $PDIR/panel/ubuntu-gnome.ini $PDIR/config.ini
# Setting Background
feh --bg-fill $PDIR/wallpaper/ubuntu.jpg
# Restarting polybar
$LAUNCH &

elif  [[ $1 = "-xubuntu" ]]; then
# Removing Old File
rm -rf $PDIR/config.ini
# Coping New File
cp -r $PDIR/panel/xubuntu.ini $PDIR/config.ini
# Setting Background
feh --bg-fill $PDIR/wallpaper/xubuntu.png
# Restarting polybar
$LAUNCH &

else
echo "Available options:
-budgie		-gnome		-mint		-ubuntu_gnome		-xubuntu"
fi
